name = "qqvvmail-server"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

routes = [
  { pattern = "apimail.qqvv.de", custom_domain = true }
]

[vars]
PREFIX = "tmp"
DOMAIN = "qqvv.de"
JWT_SECRET = "055a7a1fc9e23188577ec9a877f08b4770f4e4c6310e9ca9ffb333f35ef0766e"
ADMIN_PASSWORDS = '["198052Ab"]'

[[d1_databases]]
binding = "DB"
database_name = "cloudflare_temp_email"
database_id = "2adf1f9f-bd89-40e5-9cfc-d30207fd68f8"
